name: PullRequest

on: [pull_request]

jobs:
  buildMac:
    name: Build on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: install qt
        run: brew install qt
      - name: install build environment
        run: .ci/travis/install.sh
      - name: Build project
        run: .ci/travis/build.sh
      - name: Archive artifact
        uses: actions/upload-artifact@v2.0.1
        if: ${{ success() }}
        with:
          name: DLT-macOS
          path: build/release
